config/routes.rb
Rails.application.routes.draw do

  

  resources :answers
  resources :questions
  resources :options
  resources :surveys
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  

Rails.application.routes.draw do
    devise_for :users, controllers: {
        confirmations: 'users/confirmations',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
    }
  end
  root 'welcome#index'

    get 'teacherDashboard' => 'teacher_dashboard#home', as: :teacher_dashboard

    get 'studentDashboard' => 'student_dashboard#home', as: :student_dashboard
     
    post 'submitAnswers' => 'student_dashboard#submit_student_answer', as: :submit_student_answer

    delete '/deleteAnswers' => 'student_dashboard#destroy_student_answer'

    patch  '/submit_answer' => 'teacher_dashboard#submit_answer', as: :submit_answer

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :parent, class_name: 'Comment'
  has_many :children, class_name: 'Comment', foreign_key: 'parent_id'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
	def index
		@comments = Comment.all.where(parent_id: nil)
	end

	def new
    @comment = Comment.new(parent_id: params[:parent_id])
	end

	def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to comments_path
    else
      render 'new'
    end
	end

  private

    def comment_params
      params.require(:comment).permit(:title, :body, :author,:parent_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
	
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
  </tr>
  <% comment.children.each do |child| %>
    <tr>
      <td><%= child.body %></td>
    </tr>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :parent_id %>
 
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Join the discussion</h1>
    <p>Click the button below to start a new thread:</p>
    <p>
      <%= link_to 'Add new Review', new_comment_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<%= render @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>
<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>
<%= render 'form' %>