config/routes.rb
Rails.application.routes.draw do

  

  resources :answers
  resources :questions
  resources :options
  resources :surveys
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  

Rails.application.routes.draw do
    devise_for :users, controllers: {
        confirmations: 'users/confirmations',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
    }
  end
  root 'welcome#index'

    get 'teacherDashboard' => 'teacher_dashboard#home', as: :teacher_dashboard

    get 'studentDashboard' => 'student_dashboard#home', as: :student_dashboard
     
    post 'submitAnswers' => 'student_dashboard#submit_student_answer', as: :submit_student_answer

    delete '/deleteAnswers' => 'student_dashboard#destroy_student_answer'

    patch  '/submit_answer' => 'teacher_dashboard#submit_answer', as: :submit_answer

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	scope :most_recent, -> { order("created_at desc") }
	has_many :questions ,:dependent => :destroy
	accepts_nested_attributes_for :questions, :allow_destroy => true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  include SurveysHelper 
  
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.most_recent
  end


  # GET /surveys/1
  # GET /surveys/1.json
  def show
     @answers = Answer.new
     @questions_by_set = @survey.questions
     @questions_by_set_with_paginate = @questions_by_set.paginate(:page => params[:page], :per_page => 4) 
     respond_to do |format|
      format.html
      format.js
    end
  end

 
  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.questions.build  
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    respond_to do |format|
      if @survey.save
        students = User.with_role :student
        student_emails = students.map(&:email)  
        survey_name =@survey.name
        SurveysWorker.perform_async(student_emails,survey_name)
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.json{render json: @survey}
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name ,questions_attributes: [ :id, :content, :survey_id ,:_destroy, options_attributes: [ :id, :question_id, :is_correct,:option_text ,:_destroy]])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper

 def checked_answer(option)
   if (option.answers.present? && option.answers.find_by(user_id:current_user.id).present?)
   	 @answer = true	
   else
     @answer = false
   end
   @answer
 end

end

app/views/surveys/_form.html.erb
<%= nested_form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :questions do |questions_for_form| %>
    <%= render 'question_fields', f: questions_for_form %>
  <% end %>
  <%= f.link_to_add "Add Question",  :questions %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_option_fields.erb
<fieldset>
  <%= f.check_box :is_correct  %>
  <%= f.label "Answer" %>
  <%= f.text_area :option_text %>
  <%= f.hidden_field :_destroy %>
  <%= f.link_to_remove "remove"%>
</fieldset>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :text, "Question" %>
  <%= f.text_area :content %>
  <%= f.hidden_field :_destroy %>
  <%= f.link_to_remove "remove"%>

  <%= f.fields_for :options do |options_for_form| %>
    <%= render 'option_fields', f: options_for_form %>
  <% end %>
  <%= f.link_to_add "Add answer", :options %>
</fieldset>

app/views/surveys/_survey.html.erb
<%= form_for @survey do |f| %>
  <% @questions_by_set_with_paginate.each do |question| -%>
      <b>Question:</b><%= question.content %> <br />
      <b>Options:</b><br /> 
      <% question.options.each do |option| %>
          <% checked_answer(option)%>
          <% if current_user.has_role?"teacher"%>
      	 	   <%= f.check_box :id,  checked: option.is_correct%>
          <% else %>
            <%= check_box_tag "question[#{question.id}]", option.id, 
            @answer %>
          <%end%>
      	  <%= option.option_text %><br />
      <%end %><br />
  <% end %>
 <% if (current_user.has_role? "student") && (@questions_by_set_with_paginate.current_page == @questions_by_set_with_paginate.total_pages) %>
   <%= link_to 'submit Test',submit_answer_path(id:survey.id), method: "patch",remote: true %> 
   <br />
 <% end %> 
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
         <tr id = <%=survey.id%>> 
            <td><%= survey.name %></td>
            <td><%= link_to 'Show', survey %></td>
            <% if can? :update, @article %>
              <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
            <% end %>
            <% if can? :update, @article %>
              <td><%= link_to 'Destroy', "#",data: {id: survey.id}, class: 'survey_destroy' %></td>
            <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :update, @article %>
  <%= link_to 'New Survey', new_survey_path %>
<% end %>

app/views/surveys/new.html.erb
<h1>New Exam</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<strong>Name:</strong>
<%= @survey.name %><br/>

<div id="surveys">
  <div class="survey">
      <%= render @survey %>
  </div>

</div>



<%= will_paginate @questions_by_set_with_paginate %>

<script>

 $(document).on("change", ":checkbox", function(){
      var option_id = $(this).attr("value");
      var que = this.id.split('_').pop();
      var ans = this.value;
      var is_checked = true
      
      if($(this).is(":checked"))
        {
          
         $.ajax({
              type: "POST",
              url: '/submitAnswers',
              data: { que : que, ans : ans, is_checked: is_checked },
              success: function(data){
                 return false;
              },  
              failure: function(data){
                 return false;
              } 
          });
        }
      else
        {
          $.ajax({
              type: "DELETE",
              url: '/deleteAnswers',
              data: { option_id: option_id},
              success: function(data){
                return false;
              },  
              failure: function(data){
                return false;
              } 

          });
          return false;
        }
    });
 
</script>

app/views/surveys/show.js.erb
$('#surveys').append('<%= escape_javascript render(@survey) %>');
<% if @questions_by_set_with_paginate.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@questions_by_set_with_paginate) %>');
<% else %>
  $('.pagination').remove();
<% end %>